### ISSUE TITLE
Block/break websites

### ISSUE THREAD

**Issue by Raziel-SSJ** [uBlockOrigin/uBOL-home#90] opened 2023-11-24 23:29 UTC
Hi.
The extension block/break websites (like [1fichier.com](https://1fichier.com/)) that don't even show Ads _(and don't even have trackers according to "Firefox Privacy Protection", "NoScript" and "Privacy Badger")_.

**Comment by iam-py-test** [comment] 2023-11-25 00:28
> "NoScript" and "Privacy Badger"

Please disable all other browser extensions and see if the problem persists.
Thanks

**Comment by Raziel-SSJ** [comment] 2023-11-25 00:54
> Please disable all other browser extensions and see if the problem persists. Thanks

Already done, as well as FF-PP, but didn't work.

**Comment by gorhill** [comment] 2023-11-25 01:18
We can't help if you are not more forthcoming about what exactly is broken. The site seems to work fine as far as I could see.

**Comment by Raziel-SSJ** [comment] 2023-11-25 02:05
> We can't help if you are not more forthcoming about what exactly is broken. The site seems to work fine as far as I could see.

Sorry for not being more explicit. I was thinking this would be pretty easy to reproduce since I use lasted FF build with every other extensions disabled.
See [here](https://github.com/uBlockOrigin/uBOL-home/discussions/91#discussioncomment-7664391) for evidence.

**Comment by gorhill** [comment] 2023-11-25 02:08
It's a Firefox issue, their DNR API is not fully implemented, it does not yet support `third-party` filter option: <https://bugzilla.mozilla.org/show_bug.cgi?id=1797408>, and this is causing the issue here.

You will have to lower the filtering mode to "no filtering" for that site, until the issue is fixed in Firefox.

**Closed by gorhill** 2023-11-25 02:08 UTC
Labels: external, Firefox

**Comment by Raziel-SSJ** [comment] 2023-11-25 02:26
All right. Thanks for your answer and sorry for the annoyance.

**Comment by krystian3w** [comment] 2024-07-25 08:53
Looks fixed in 128+:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/RuleCondition#browser_compatibility

So possible start test change filtering to "basic" / "simple" / "complete" by **Raziel-SSJ** if can jump from Firefox 127 to 128 or ESR 115.13 to ESR 128 (needed upgrade Windows and macOS if we don't like forks like R3dfox/vyvfox and luminafox).

**Comment by Raziel-SSJ** [comment] 2024-08-04 17:36
> Looks fixed in Firefox 128+:

Thanks @krystian3w for letting me know.
The issue is indeed fixed now.

_Though, I still think that "No Filtering" should be a possible default behavior option._ 😅

**Comment by krystian3w** [comment] 2024-08-04 17:42
Recently added: https://github.com/uBlockOrigin/uBOL-home/issues/150#issuecomment-2233379095

You can see if that's what you mean, unless this page is updated too quickly for the limit of statically compiled DNR rules.

**Comment by Raziel-SSJ** [comment] 2024-08-04 18:12
> Recently added: [#150 (comment)](https://github.com/uBlockOrigin/uBOL-home/issues/150#issuecomment-2233379095)
> 
> You can see if that's what you mean, unless this page is updated too quickly for the limit of statically compiled DNR rules.

Oh yeah, that's exactly what I was looking for.
Many thanks for pointing this to me. I'll give it a try.
