### ISSUE TITLE
steamcommunity.com: breakage

### ISSUE THREAD

**Issue by growf** [uBlockOrigin/uBOL-home#156] opened 2024-07-27 15:56 UTC
**OS:** macOS Sonoma 14.5 (23F79)
**Browser:** Google Chrome 126.0.6478.127 (Official Build) (arm64)
**Extension:** uBlock Origin Lite 2024.7.17.853

Following a link from a Discord server to [https://steamcommunity.com/id/customurlasd/myworkshopfiles/?appid=293760](https://steamcommunity.com/id/customurlasd/myworkshopfiles/?appid=293760) is blocked despite being a genuine page on the Steam Community Workshop. uBOL blocks the link unless the filtering mode for `steamcommunity.com` is set to "No filtering".

The URL _isn't_ blocked if cut-and-pasted directly into the browser's URL bar; the block only occurs when following a link from a Discord server. I believe it is being caught up in the attempt to block fraudulent links used in Discord Nitro scams.

Issue can be worked-around by cut-and-pasting the URL in the URL bar or by disabling filtering for `steamcommunity.com`.

**Edit:** Issue appears not to be restricted to Discord links; even the link in this comment results in the page being blocked.

**Comment by growf** [comment] 2024-07-27 16:07
#155 doesn't have the specific replication steps that this issue does; this ticket is specifically related to Discord links to steamcommunity.com

Additionally, I am not running a second ad-blocker.

**Comment by growf** [comment] 2024-07-27 16:12
Huh. Even the link _from this ticket's description_ is blocked.

**Comment by gorhill** [comment] 2024-07-27 22:12
> Issue can be worked-around by cut-and-pasting the URL in the URL bar or by disabling filtering for `steamcommunity.com`

Or just forcing a reload of the page.

Will have to figure out which DNR rule is causing this.

**Comment by stephenhawk8054** [comment] 2024-07-27 22:36
@gorhill There's a regex filter related to it

```adb
/^https:\/\/stea[a-z]{1,4}o[mn][a-z]{4,7}y[a-z]?\.com\//$doc,domain=com|~steamcommunity.com
```

Could it cause issue because DNR does not support `~steamcommunity.com` yet?

**Comment by gorhill** [comment] 2024-07-28 14:12
DNR does support `~`, the rule is here using `excludedInitiatorDomains`: <https://github.com/uBlockOrigin/uBOL-home/blob/main/chromium/rulesets/regex/default.json#L99>. It could be though that the initiator is evaluated differently in DNR.

Note that I cannot reproduce when compiling the extension locally, so it seems a filter which was removed is causing this.

**Comment by stephenhawk8054** [comment] 2024-07-28 14:53
Hmm... even when I modify the link to just `https://steamcommunity.com`, it's still blocked. But weird that the document when reloading is fine.

**Comment by gorhill** [comment] 2024-07-28 15:46
Weird, I cannot reproduce with locally-compiled and sideloaded MV3 in Chromium, but can reproduce with locally-compiled and sideloaded MV3 in Firefox.

I can reproduce when sideloading both [latest release](https://github.com/uBlockOrigin/uBOL-home/releases/tag/uBOLite_2024.7.28.888) for Chromium and Firefox.

Will need a way to report triggered rules at the console to figure out which rule is causing the issue.

**Comment by gorhill** [comment] 2024-07-28 16:42
Turns out my sideloaded Chromium version was suffering from an unrelated bug related to entering `all-urls` in the "No filtering" field, preventing me from reproducing locally in Chromium. Removing the `all-urls` from the "No filtering" field did not cause the rule which disables blocking averywhere by default to be removed. This will have to be fixed separately.

Now I can reproduce locally in Chromium, and the reported rule which is causing the issue is:

```
[uBOL] https://github.com => https://steamcommunity.com/id/customurlasd/myworkshopfiles/?appid=293760
	[{"action":{"type":"block"},"condition":{"excludedInitiatorDomains":["steamcommunity.com"],"initiatorDomains":["com"],"regexFilter":"^https:\\/\\/stea[a-z]{1,4}o[mn][a-z]{4,7}y[a-z]?\\.com\\/","resourceTypes":["main_frame"]},"id":1000071}]
```

So the issue is that the `initiator` as seen by the DNR API is `github.com`.

**Comment by stephenhawk8054** [comment] 2024-07-28 16:52
Hmm... DNR `initiator` is quite different than what I expected. I thought it means the context of the page. Didn't know it means the page before that.

**Comment by stephenhawk8054** [comment] 2024-07-29 02:09
I'll use `!env_mv3` as a temp solution

**Comment by gorhill** [comment] 2024-07-29 12:04
I think using `to=com|~steamcommunity.com` instead of `domain=com|~steamcommunity.com` should work.

**Comment by stephenhawk8054** [comment] 2024-07-29 12:18
Hmm... I'm still not clear about DNR `domain`. For example there's a filter in badware list like this

```adb
/\/[0-9a-f]{32}\/maq\/$/$doc,match-case,domain=com|top
```

If a user visits 

```yml
https://example.org
``` 

then click on a link that is 

```yml
https://example.com/11111111111111111111111111111111/maq/
```

so would the `maq` link be blocked? The `domain` here will be referred to `https://example.com` or `https://example.org`?

**Comment by gorhill** [comment] 2024-07-29 12:51
Since the filter is targeted at `document` requests, using `to=` make more sense in that case since you want to block the request regardless of its initiator -- this will make the filter work properly in uBOL Lite while still working properly in uBO.

**Comment by stephenhawk8054** [comment] 2024-07-29 13:04
Hmm... Currently there are a lot of filters with `domain` and `doc`, so are they all potentially having issues in uBOL?

---

Also there's a weird situation I'm getting, related to `doc` and `domain` while I was testing with the above `example.org`: currently this link is blocked properly in uBO: `https://example.com/c/a?s1=1` due to the filter 

```adb
.com/c/*?s1=$document,domain=com
```

But when I open it in uBOL, it's not blocked, although the filter is compiled to DNR normally

```
{"action":{"type":"block"},"condition":{"initiatorDomains":["com"],"resourceTypes":["main_frame"],"urlFilter":".com/c/*?s1="},"id":10772}
```

I found that when I modified the link "More information" in `https://example.org` to `https://example.com/11111111111111111111111111111111/maq/` and clicked on it, the link was not blocked. Then I just load the whole link in the URL bar and it's not blocked either.

**Comment by stephenhawk8054** [comment] 2024-07-29 14:19
Thanks. It's more complicated than I expected now that I think about the filters which have both `domain` and `to`.

cc @Yuki2718 , these may be useful for badware list.

**Comment by gorhill** [comment] 2024-07-29 14:36
Just to be clear, `domain=` is still needed for filters targeting resources other than `document`.

**Comment by stephenhawk8054** [comment] 2024-07-29 14:42
Yeah I understand. The only tricky ones are `document` and maybe `all`? There are some filters like

```adb
||fitgirl-repacks.*^$all,domain=~fitgirl-repacks.site,to=~fitgirl-repacks.site
```

that I'm not actually sure how it will perform in uBOL.

**Comment by Yuki2718** [comment] 2024-07-29 14:54
I guess we need to a lot of `$domain` to `$to` then. Not only Badware, I have to Change Japanese filter too (confirmed the behviro is the same for AGMV3).

**Comment by stephenhawk8054** [comment] 2024-07-31 15:45
Confirm switching `doc,domain=` to `doc,to=` works.

cc @Yuki2718 We can gradually switch to this format

**Comment by gorhill** [comment] 2024-08-05 18:15
Fixed in latest stable release <https://github.com/uBlockOrigin/uBOL-home/releases/tag/uBOLite_2024.8.5.925>.

**Closed by gorhill** 2024-08-05 18:15 UTC

**Comment by stephenhawk8054** [comment] 2025-03-03 15:18
@gorhill Hmm... About `domain` and `to` issue, is `removeparam` affected the same? Many of the filters in "AdGuard URL Tracking Protection" is like this:

```adb
.com/*/status/$removeparam=t,domain=twitter.com|x.com
```

Should they be changed to `.com/*/status/$removeparam=t,to=twitter.com|x.com` ?

**Comment by gorhill** [comment] 2025-03-03 15:39
Yes.

I get expected result when using `?appid=$removeparam=appid,to=example.com` and either clicking or copy-pasting into address bar <https://example.com/?appid=toto>, and unexpected result when using `?appid=$removeparam=appid,to=example.com`.

**Comment by gorhill** [comment] 2025-03-03 15:50
I could internally convert `domain=` to `to=` in uBOL for `removeparam` option.

**Comment by Yuki2718** [comment] 2025-03-04 09:19
AGMV3 doesn't remove either. I'll open an issue.
