### ISSUE TITLE
Outlook Ads

### ISSUE THREAD

**Issue by cscribn** [uBlockOrigin/uBOL-home#41] opened 2023-05-08 13:30 UTC
When visiting outlook.live.com, using Chrome on Windows with uBOL and "complete", the email ad and right page are visible.

![Outlook](https://user-images.githubusercontent.com/7039129/236836494-6624acfc-5a0b-4974-8602-b3da7eef8fc6.png)

**Comment by gorhill** [comment] 2023-05-08 14:00
Duplicate of <https://github.com/uBlockOrigin/uAssets/discussions/17566>. Solutions for uBO are being discussed there.

**Closed as completed by gorhill** 2023-05-08 14:00 UTC
Labels: duplicate
