### ISSUE TITLE
Badge counter reports broken data

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBOL-home#147] opened 2024-07-05 17:09 UTC
Chrome version 126.0.6478.127 with uBlock Origin Lite 2024.7.3.674
It isn't actually blocking anything, just the counter shows wrong info.
![Capture](https://github.com/uBlockOrigin/uBOL-home/assets/104303586/3e226c20-dade-4924-84f5-719aecbbb5f1)

**Comment by gorhill** [comment] 2024-07-05 17:23
How did you determine it's not blocking anything?

Most likely duplicate of <https://github.com/uBlockOrigin/uBOL-home/issues/20>.

**Comment by sosilly2004** [comment] 2024-07-05 17:38
> How did you determine it's not blocking anything?

I am using Chrome's devtool to monitor blocked network requests. The badge counter is stuck at 1 on YouTube. Restarting the browser or doing a hard refresh is fixing it for that session.

> Most likely duplicate of #20.

I read the issue and it sounds similar. You may close this one if you want.

> By the way, the badge counter is driven by the browser through its DNR API, uBOL does not touch it.

Ah, I see. Thank you for the heads up.

**Closed** 2024-08-05 18:32 UTC
Labels: duplicate
