### ISSUE TITLE
Add the "no filtering" mode to the default filtering mode selection

### ISSUE THREAD

**Issue by ArtyIF** [uBlockOrigin/uBOL-home#235] opened 2024-10-18 18:06 UTC
The browser I use (Vivaldi) has a built-in ad blocker that generally works fine, except for YouTube, where it struggles with the anti-adblock popup. For other sites, Vivaldi's own ad blocker works just fine. I'd like to have an option in the dashboard to set uBOL's filtering to "no filtering" in this case.

**Comment by gorhill** [comment] 2024-10-18 18:34
Duplicate of <https://github.com/uBlockOrigin/uBOL-home/issues/150>.

**Closed by gorhill** 2024-10-18 18:34 UTC

**Comment by ArtyIF** [comment] 2024-10-18 21:07
Oh wow, didn't know about the `all-urls` thing. It should be documented more clearly in the dashboard then, maybe add it to the example domains. Before that I tried an asterisk and it didn't work.

**Comment by stephenhawk8054** [comment] 2024-10-19 00:00
> This is as far as I will go to support that special mode, i.e. I won't further modify the user interface to specifically enable no filtering as default mode.
