### ISSUE TITLE
The extension failed to load properly. It might not be able to intercept network requests.

### ISSUE THREAD

**Issue by TESTER-sec** [uBlockOrigin/uBOL-home#199] opened 2024-09-06 02:07 UTC
![image](https://github.com/user-attachments/assets/be926d63-872c-491f-8735-4c93661f9dab)

![image](https://github.com/user-attachments/assets/0a5f1345-5d7c-4638-a73f-434f31039760)

**Comment by gorhill** [comment] 2024-09-06 03:58
Do you have other content blocking extensions installed -- disabled included?

**Comment by garry-ut99** [comment] 2024-09-06 08:02
> TESTER-sec

Don't spam with duplicates, next time post in already existing threads, search issue tracker before creating a new thread (and if you did it, do it better next time), a duplicate of:
- https://github.com/uBlockOrigin/uBOL-home/issues/109

**Comment by garry-ut99** [comment] 2024-09-06 11:16
The rule on the original uBO tracker is to tick checkbox:
>  * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=sort%3Aupdated-desc+is%3Aissue) to avoid opening a duplicate issue.

means duplicate threads are considered spam, that's a technical fact, that cannot be denied, there is no such a template on uBOL tracker, but I guess the same rules should apply here as well.

> TESTER-sec: Be better, instead of being a jackass

Calm down jackass, you seem to very aggressive toward me, I didn't call you names, you're calling me names, take a breath, go a walk, and stop your off-topic personal attack, how old are you, grow up child.

> TESTER-sec: to people that are giving you their free time to help your project.

You seem to be very egoistic and narcistic, as actually it works the opposite as well: developers and volunteers like me are these who give their free time to help people like you, I waste my time to find duplicated threads.

<hr>

By the way:

<details>
<summary>SPOILER</summary>

now due to your personal off-topic and attack, from which I had no other choice than to defend myself, my comment will be hidden and marked as off-topic, while your comment will be most likely not, just because it contains some on-topic, apart of off-topic, just like in previous case: https://github.com/uBlockOrigin/uBlock-issues/issues/3362#issuecomment-2324035883, not to mention it's you who caused thw whole off-topic (including my reply). If mixing some on-topic content to an off-topic content causes a comment to not be hidden by moderators, which means your personal attack and calling names won't be hidden and will stay visible, while my reply will stay hidden, then I don't like how moderation is done, and I must consider adding some on-topic to every of my reply, to not let it be hidden. The best would be if moderators would hide off-topic personal attacks by collapsing them into a spoiler, and leaving only on-topic part, otherwise it's not fair to leave calling names publicly visible.

</details>

**Comment by gorhill** [comment] 2024-09-06 12:45
@garry-ut99 There is no need to immediately qualify duplicates as spam unless it is obvious spam. Duplicates happen, there is no need go straight to accusation of spam, this just poisons immediately the discussion. Just pointing out this is possibly a duplicate is enough, ultimately I will decide whether to close it as duplicate or not.

Also please refrain from linking the comments on your personal repo to discussion here, they accomplish nothing for the project, there is no valuable information for people exploring issues here; use code block to encode your links to avoid polluting the discussions with backlinks to your personal journal.

**Comment by gorhill** [comment] 2024-09-06 12:50
> No. Just uBOL.

Given this, I will confirm this as duplicate of #109. Sometimes when the extension update there "internal error" reported at the console. Restarting the extension fixes the issue. This is out of control of uBOL, as the error occurs somewhere in the browser's extension framework.

**Comment by garry-ut99** [comment] 2024-09-07 15:12
> https://github.com/uBlockOrigin/uBOL-home/issues/199#issuecomment-2333765474

Again. I didn't call him names (not as first), he did call me names. Even if I said something which he didn't like, Me, as a valuable volunteer here, didn't deserve to be called names, and he could express his opinion without calling names.  The same applies to this comment as well: `https://github.com/uBlockOrigin/uBlock-issues/issues/3362#issuecomment-2324035883`. Not to mention that their comments have been not hidden (not all), while my have been hidden, which is nothing more than inconsistency in moderation. They both + moderation acted like aggressive jackasses towards me.

**Comment by gorhill** [comment] 2024-09-22 16:22
I was able to reproduce the issue in my local build as I prepared for a new release.

The previously committed code didn't work as expected, and since I was to reproduce at will (as long as a force-reload of the extension was not performed), I could this test the code which purpose is to work around the issue. So this is confirmed fixed with <https://github.com/gorhill/uBlock/commit/ff57f01026f1b98ca9d9a8bb36386ae9dfd3eae3>.

**Closed** 2024-09-26 16:55 UTC
Labels: fixed
