### ISSUE TITLE
Deploying via GPO. Is there a way to suppress_first_run_page ?

### ISSUE THREAD

**Issue by jadambcbc** [uBlockOrigin/uBOL-home#186] opened 2024-08-20 19:29 UTC
Hi there, thanks for this great extension. Attempting to migrate my company from uBlock Origin to lite. 

We deploy origin via a Group Policy as force-installed extension. This works for lite as well. 

However with Origin there is a registry key called suppress_first_run_page , so that users aren't confused by this and opening support tickets. 

is there a similar registry key or option somehow to suppress the dashboard/page after installing the extension?
thanks!

**Comment by iam-py-test** [comment] 2024-08-20 20:27
> However with Origin there is a registry key called suppress_first_run_page

uBlock Origin doesn't have a page which opens on installation, and no registry key with that name is mentioned in the documentation for either extension. Moreover, both extensions use camel case.
In any case, this documentation should be helpful: https://github.com/uBlockOrigin/uBOL-home/wiki/Managed-settings
Thank you

**Comment by garry-ut99** [comment] 2024-08-21 13:58
> jadambcbc: Deploying via GPO. Is there a way to suppress_first_run_page ? 

Duplicate of:
- https://github.com/uBlockOrigin/uBOL-home/issues/146
- https://github.com/uBlockOrigin/uBOL-home/discussions/61

Also related discussion:
- https://github.com/uBlockOrigin/uBOL-home/discussions/35

**Comment by gorhill** [comment] 2024-08-21 14:23
> In any case, this documentation should be helpful: https://github.com/uBlockOrigin/uBOL-home/wiki/Managed-settings

Closing, as this is already documented.

**Closed** 2024-08-21 14:23 UTC
