### ISSUE TITLE
imdb.com: breakage

### ISSUE THREAD

**Issue by alturic** [uBlockOrigin/uBOL-home#185] opened 2024-08-16 13:44 UTC
As the title says, visiting imdb.com with a video on the page (https://www.imdb.com/name/nm0000498/? as an example) results it a mass spam of the video fetches which then leads to getting 503'd for ~minute. I'm unsure if this is something specific to how uBOL works (using all filters but the region-specific ones) or if it's crap JS on the end of imdb.

**Comment by gorhill** [comment] 2024-08-16 17:56
Issue is related to the following two filters:

    *$media,redirect=noopmp3-0.1s,domain=imdb.com,3p
    @@||media-imdb.com^$media,domain=imdb.com

In the conversion to DNR rules, the `redirect` filter has priority over the exception filter while this should not be the case.

The conversion needs to ensure that exception filters have priority over `redirect` filters, which is currently not the case.

**Comment by alturic** [comment] 2024-08-16 18:04
Thanks for the amazingly quick find! I am curious however, is this something specific to the way imdb is coded or something else? It's the only site that I've seen anything like this happen to.

Also, just out of curiosity, and no I don't *expect* anything from OSS, is this something that would make the fix in the next update?

**Comment by gorhill** [comment] 2024-08-16 18:14
The fix will be in next update, the issue is not converting properly exception filters into DNR rules.

**Comment by stephenhawk8054** [comment] 2024-08-17 03:34
I think this can also be addressed by adjusting the filters to

```adb
*$media,3p,redirect=noopmp3-0.1s,from=imdb.com,to=~media-imdb.com
```

?

**Comment by gorhill** [comment] 2024-08-17 14:59
Yes, this will also work. Still need to fix the exception issue though.

**Comment by gorhill** [comment] 2024-08-19 16:55
Fixed in [uBOLite_2024.8.19.905](https://github.com/uBlockOrigin/uBOL-home/releases/tag/uBOLite_2024.8.19.905)

**Closed by gorhill** 2024-08-19 16:55 UTC
Labels: bug
