### ISSUE TITLE
Missing filters from original uBO

### ISSUE THREAD

**Issue by x-rated** [uBlockOrigin/uBOL-home#128] opened 2024-04-23 11:47 UTC
Without the other filters from uBO the blocking results are quite poor 😔 For example seznam.cz, mapy.cz, novinky.cz - detected and not possible to enter, telekomunikace.cz - top ads not blocked etc.

**Comment by gorhill** [comment] 2024-04-23 16:01
If you want me to look into this, you need to:

- Provide the filter lists selected on your side
- Provide me an exact URL where I can see for myself "detected and not possible to enter"
- Provide the filtering mode selected for the site

**Comment by x-rated** [comment] 2024-04-23 16:15
I have all filters enabled and in case of regional i use cz & sk only, with complete filtering: https://imgur.com/a/jnZWYSq
https://www.seznam.cz, https://www.mapy.cz, https://www.novinky.cz and some others from same company: https://i.imgur.com/gWUP0yA.png
telekomunikace.cz: https://i.imgur.com/tkNDFVD.png
thank you 🙂

**Comment by gorhill** [comment] 2024-04-23 16:35
Which browser/version is this?

**Comment by x-rated** [comment] 2024-04-23 16:39
Chrome 125.0.6422.4 (beta)
I usually use stable, but on 124 Skia Graphite flag doesnt work 😐

**Comment by gorhill** [comment] 2024-04-23 16:39
With the information you gave me, I can't see any issue. I need the most straightforward way to reproduce on my side, i.e, please do not provide cropped screenshots out of context. I need an exact URL, the screenshot of the page with the problematic section highlighted. Basically, I won't try to guess how to reproduce, I will investigate only if I can reproduce with the details you provide me.

I loaded `https://www.seznam.cz/` in the address bar and I can't see anything obvious which resemble an issue when using default list + _"EasyList Czech and Slovak"_ in _Optimal_ mode.

**Comment by gorhill** [comment] 2024-04-23 16:42
> telekomunikace.cz: https://i.imgur.com/tkNDFVD.png

I can see the banner in your screenshot with uBO, so it's expected it will be also present with uBOL. You need to report to maintainers of _EasyList Czech and Slovak_.

**Comment by x-rated** [comment] 2024-04-23 16:45
after entering seznam.cz (and others mentioned), it redirects to https://cmp.seznam.cz/nastaveni-souhlasu
https://i.imgur.com/SZC9zYy.png

and regarding telekomunikace.cz, its this block of ads on top of the page https://i.imgur.com/VaQD4Xk.png

**Comment by gorhill** [comment] 2024-04-23 16:52
> after entering seznam.cz (and others mentioned), it redirects to https://cmp.seznam.cz/nastaveni-souhlasu
https://i.imgur.com/SZC9zYy.png

Dan Pollock is causing this on my side.

**Comment by gorhill** [comment] 2024-04-23 17:04
Dan Pollock contains this entry, `h.seznam.cz`, so it's expected `https://h.seznam.cz/js/cmp2/scmp-cw.js`. What is not expected is that the same entry with Pollock enabled in uBO is not being blocked.

**Comment by stephenhawk8054** [comment] 2024-04-24 00:16
> badfilter as is not possible in uBOL, except within same list.

Hmm... Does that mean the `badfilter` in Unbreak list which tackles other lists is discarded in uBOL?

**Comment by gorhill** [comment] 2024-04-24 10:47
> which tackles other lists is discarded in uBOL?

It's discarded for other lists not part of the same DNR ruleset, so it works fine for EasyPrivacy, EasyList, Peter Lowe since they are all part of the default ruleset along with uBO's lists. It does not work for Dan Pollock and others. I am a bit surprised though that we have these `badfilter` entries seemingly addressing issues in non-default lists -- I thought the policy was to not address such issues in _Unbreak_.

**Comment by gorhill** [comment] 2024-08-05 18:29
If a site is broken by a list maintained elsewhere than uAssets, this needs to be fixed in that list. The fact that the issue from an external list was fixed in uBO's default lists, typically this should not be the case.

In short, if Dan Pollocks' `h.seznam.cz` breaks a website, this needs to be reported and fixed in Dan Pollocks' list.

**Closed by gorhill** 2024-08-05 18:29 UTC
Labels: bug, mv3 hardship
