### ISSUE TITLE
Element picker blocker

### ISSUE THREAD

**Issue by MeechaPooch** [uBlockOrigin/uBOL-home#215] opened 2024-09-29 08:13 UTC
Can you add the feature from UBO to pick html elements from the page and perminently block them? Its a super important feature. I use it for blocking the instagram feed and such.
<img width="77" alt="image" src="https://github.com/user-attachments/assets/263f2fd2-c449-45b3-9498-95495a7d6701">

**Comment by gorhill** [comment] 2024-09-29 12:41
Duplicate of <https://github.com/uBlockOrigin/uBOL-home/issues/17>.

**Closed by gorhill** 2024-09-29 12:41 UTC

**Comment by garry-ut99** [comment] 2024-10-03 10:30
Also many same threads with additonal information:
