### ISSUE TITLE
Interaction with Zotero extension, prevents connection

### ISSUE THREAD

**Issue by abhiaagarwal** [uBlockOrigin/uBOL-home#179] opened 2024-08-14 14:36 UTC
Hi there,

I'm using UBO-Lite on my personal machine. I'm attempting to have my Zotero Connector connect to said Zotero instance on my laptop, but it doesn't appear to work with UBO enabled. For context, the extension attempts to POST to `http://127.0.0.1:23119/connector/ping`, but this is blocked when UBO is enabled. Disabling the UBO extension fixes this. Even attempting to whitelist `127.0.0.1` and `localhost` doesn't resolve the issue.

This might be related to #20.

**Comment by stephenhawk8054** [comment] 2024-08-14 14:46
Which filter lists are you enabling in uBOL?

**Comment by abhiaagarwal** [comment] 2024-08-14 14:58
<img width="488" alt="Screen Shot 2024-08-14 at 8 25 58 PM" src="https://github.com/user-attachments/assets/a00ab632-b537-4f71-a426-bddc3cbeed05">

It looks like disabling "Block Outsider Intrusion into LAN" solved my issue, but I'm still not sure why even when I manually disabled the extension for localhost, it was still blocked. Maybe I was whitelisting the wrong thing?

**Comment by gorhill** [comment] 2024-08-14 15:05
Duplicate of <https://github.com/uBlockOrigin/uBOL-home/issues/169>.

**Closed by gorhill** 2024-08-14 15:05 UTC
